// app/layout.tsx

import "@/utils/fontawesome"; // ✅ Font Awesome config
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Nunito } from "next/font/google";
import "./globals.css";

import Header from "@/ui/Header";
import Footer from "@/ui/Footer";

// ✅ Set up Google Font
const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-family",
  weight: ["400", "500", "600", "700"],
});

// ✅ Site-wide metadata
export const metadata: Metadata = {
  title: "Hashi Ekshathe",
  description: "Generated by create next app",
};

// ✅ Root layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={nunito.variable}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
